# Generated by Django 4.2 on 2026-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="notes_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
