# Generated by Django 4.2 on 2026-01-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="subject",
            field=models.CharField(default="General", max_length=20),
        ),
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="notes_files/"),
        ),
    ]
