# Generated by Django 4.2 on 2026-01-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_code",
            field=models.CharField(
                choices=[("11", "Class 11"), ("12", "Class 12")],
                default=11,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
