# Generated by Django 4.2 on 2026-01-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[("11", "Class 11"), ("12", "Class 12")],
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="teaching_class",
        ),
        migrations.AddField(
            model_name="teacher",
            name="classes",
            field=models.ManyToManyField(
                related_name="teachers", to="teachers.teacherclass"
            ),
        ),
    ]
