# Generated by Django 4.2 on 2026-01-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("subjects", "0001_initial"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "subject", "date")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_present",
        ),
    ]
