# Generated by Django 4.2 on 2026-01-27 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_present_alter_attendance_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="class_code",
            field=models.CharField(default=11, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
