# Generated by Django 4.2 on 2026-01-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="class_name",
            field=models.CharField(
                choices=[("11", "Class 11th"), ("12", "Class 12th")],
                default=11,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
