# Generated by Django 4.2 on 2026-01-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0003_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_view_count",
            field=models.IntegerField(default=1),
        ),
    ]
