# Generated by Django 4.2 on 2026-01-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0005_department_studentid_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Student_address",
            new_name="student_address",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="Student_age",
            new_name="student_age",
        ),
    ]
