# Generated by Django 4.2 on 2026-01-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0007_subject_studentmarks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentMarks",
            new_name="SubjectMarks",
        ),
    ]
