# Generated by Django 4.2 on 2026-01-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0009_reportcard"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student_rank", "date_of_generation")},
        ),
    ]
