# Generated by Django 4.2 on 2026-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0010_alter_reportcard_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="date_of_generation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
